import math
import random


class SecretNumber:
    """Represents the secret number generated by the system."""

    def __init__(self, min_val=0, max_val=100):
        self.value = random.randint(min_val, max_val)

    def is_even(self) -> bool:
        return self.value % 2 == 0

    def is_prime(self) -> bool:
        if self.value < 2:
            return False
        for i in range(2, int(math.isqrt(self.value)) + 1):
            if self.value % i == 0:
                return False
        return True

    def is_perfect_square(self) -> bool:
        root = math.isqrt(self.value)
        return root * root == self.value


class User:
    """Represents the player and manages their remaining attempts."""

    def __init__(self, max_attempts=10):
        self.attempts = max_attempts

    def reduce_attempt(self):
        self.attempts -= 1

    def has_attempts(self) -> bool:
        return self.attempts > 0


class Hint:
    """Handles logic for hints requested by the user."""

    @staticmethod
    def process_hint(choice: str, secret_number: SecretNumber):
        if choice == "1":
            status = "EVEN" if secret_number.is_even() else "ODD"
            print(f"\n💡 HINT: The secret number is {status}.\n")
        elif choice == "2":
            status = "a PRIME" if secret_number.is_prime() else "NOT a prime"
            print(f"\n💡 HINT: The secret number is {status} number.\n")
        elif choice == "3":
            status = (
                "a PERFECT SQUARE"
                if secret_number.is_perfect_square()
                else "NOT a perfect square"
            )
            print(f"\n💡 HINT: The secret number is {status}.\n")


class Game:
    """Main game coordinator managing user interaction and state."""

    def __init__(self):
        self.secret_number = SecretNumber(0, 100)
        self.user = User(10)

    def display_menu(self):
        print(f"Remaining Guess Attempts: {self.user.attempts}")
        print("--- MENU OPTIONS ---")
        print(" 1. Ask if the number is EVEN or ODD")
        print(" 2. Ask if the number is PRIME")
        print(" 3. Ask if the number is a PERFECT SQUARE")
        print(" 4. Make a direct GUESS")

    def play(self):
        print("=== CLASS-BASED NUMBER GUESSING GAME ===")
        print("The system has picked a secret number between 0 and 100.")
        print("You have exactly 10 attempts to guess it.\n")

        while self.user.has_attempts():
            self.display_menu()
            choice = input("Select an option (1-4): ").strip()

            if choice in ["1", "2", "3"]:
                Hint.process_hint(choice, self.secret_number)

            elif choice == "4":
                try:
                    guess = int(input("Enter your guess: "))
                except ValueError:
                    print("⚠️ Invalid input! Please type an integer.\n")
                    continue

                if guess == self.secret_number.value:
                    print(
                        f"\n🎉 CONGRATULATIONS! You won! The number was {self.secret_number.value}."
                    )
                    break
                elif guess < self.secret_number.value:
                    print("\n❌ WRONG! Try a HIGHER number.\n")
                else:
                    print("\n❌ WRONG! Try a LOWER number.\n")

                self.user.reduce_attempt()
            else:
                print("⚠️ Invalid option! Choose between 1 and 4.\n")

        if not self.user.has_attempts():
            print(
                f"\n💀 GAME OVER! You ran out of attempts. The secret number was: {self.secret_number.value}"
            )


if __name__ == "__main__":
    game = Game()
    game.play()
